config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "cars#index"

  resources :cars do
    resources :bookings, only: [:new, :create]
  end

  namespace :profile do
    resources :bookings, only: [:index, :show, :update]
    resources :cars
    root to: "cars#index"
  end

end

app/views/shared/_booking_state.html.erb
<% if booking_state == "pending" %>
  <span class="text-warning">En attente</span>
<% elsif booking_state == "accepted" %>
    <span class="text-success">accepter</span>
<% elsif booking_state == "declined" %>
    <span class="text-danger">Refuser</span>
<% elsif booking_state == "cancelled" %>
    <span class="text-secondary">Annuler</span>
<% elsif booking_state == "completed" %>
    <span class="text-success">Compléter</span>
<% elsif booking_state == "reviewed" %>
    <span class="text-success"><strong>Approuvé</strong></span>
<% end %>

app/views/shared/_bookings_list.html.erb
<div class="row">
  <% @bookings.each do |booking| %>
    <div class="col-md-3 mb-4">
      <%= link_to profile_booking_path(booking), style: 'color: inherit; text-decoration: none;' do %>
        <div class="d-flex justify-content-between flex-column rounded-4">
          <%= render 'shared/image_carousel', carousel_id: booking.id, photos: booking.car.photos %>
          <p class="fs-4 mb-0 fw-medium"><span class="fw-bold"><%= booking.car.brand %></span> - <%= render 'shared/booking_state', booking_state: booking.state %></p>
          <p class="mb-0"><%= booking.car.model %></p>
          <p class="fs-6 mb-0"><strong><%= number_with_delimiter(booking.car.price_per_day, delimiter: ',', separator: '.') %>€</strong>/jour</p>
          <p class="mb-0 fs-6">Date de location: <strong><%= booking.start_date.strftime("%d/%m/%Y") %></strong></p>
          <p class="mb-0 fs-6">Total: <strong><%= number_with_delimiter(calculate_amout_paid(booking), delimiter: ',', separator: '.') %>€</strong></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_cars_list.html.erb
<div class="row">
  <% count = 0 %>
  <% @cars.each do |car| %>
    <% if Time.now.wday == 5 && count >= 6 %>
      <% break %>
    <% end %>
    <div class="col-md-3 my-4">
      <%= link_to car_path(car), style: 'color: inherit; text-decoration: none;' do %>
        <div class="d-flex justify-content-between flex-column rounded-4">
          <%= render 'shared/image_carousel', carousel_id: car.id, photos: car.photos %>
          <p class="fs-4 mb-0 fw-medium"><span class="fw-bold"><%= car.brand %></span></p>
          <p class="mb-0"><%= car.model %></p>
          <p class="fs-6 mb-0"><strong><%= number_with_delimiter(car.price_per_day, delimiter: ',', separator: '.') %>€</strong>/Jour</p>
        </div>
      <% end %>
    </div>
    <% count += 1 %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_image_carousel.html.erb
<div id="carousel-<%= carousel_id %>" class="carousel slide">
  <div class="carousel-indicators">
    <% photos.each_with_index do |photo, index| %>
      <button type="button" data-bs-target="#carousel-<%= carousel_id %>" data-bs-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>" aria-current="<%= index == 0 ? 'true' : 'false' %>" aria-label="Slide <%= index + 1 %>"></button>
    <% end %>
  </div>
  <div class="carousel-inner">
    <% photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= cl_image_tag photo.key, height: 400, width: 600, crop: :fill, class: "img-fluid rounded-4 w-100" %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= carousel_id %>" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Retour</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= carousel_id %>" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Suivant</span>
  </button>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if !current_user.bookings.empty? || !current_user.rented_bookings.empty? %>
            <li class="nav-item">
              <%= link_to "Mes réservations", profile_bookings_path, class: "nav-link px-3" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "#{current_user.first_name + ' ' + current_user.last_name}", profile_root_path, class: "nav-link px-3" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag current_user.photo.key, class: "avatar", width: 40, height: 40, crop: :fill %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Ajouter une place", new_profile_car_path, class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_show_car.html.erb
<div class="row">
  <!-- Car Image Carousel Card -->
  <div class="col-md-7 my-4">
    <div class="rounded-4">
      <div class="card-body">
        <%= render 'shared/image_carousel', carousel_id: @car.id, photos: @car.photos %>
      </div>
    </div>
  </div>

  <!-- Car Information Card -->
  <div class="col-md-5 my-4 " width="30%">
    <div class="rounded-4">
      <div class="card-body">
        <p class="fs-4 mb-0 fw-medium">
          <span class="fw-bold"><%= @car.brand %></span>
        </p>
        <p class="mb-0"><%= @car.model %></p>
        <p class="fs-6 mb-0">
          <strong><%= number_with_delimiter(@car.price_per_day, delimiter: ',', separator: '.') %>€</strong>/Jour
        </p>
        <!-- add the full name of the user -->
        <p class="fs-6 mb-0"><%= @car.user.first_name%> <%= @car.user.last_name %></p>

      </div>
    </div>
    <div class="mt-4">
      <%= link_to "Réserver l'emplacement", new_car_booking_path(@car), class: "btn main-btn" %>
      <% if @car.user == current_user %>
        <%= link_to 'Supprimer', profile_car_path(@car), data: { turbo_method: :delete, turbo_confirm: "Etes-vous sûr ?" }, method: :delete, class: "btn danger-btn" %>
      <% end %>
      <%= link_to 'Retour', request.referer, class: "btn secondary-btn" %>
    </div>
  </div>
</div>

app/views/shared/_star.html.erb
<svg width="50px" height="50px" class="star <%= star_filled ? 'star-filled' : 'star-empty' %>" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M11.2691 4.41115C11.5006 3.89177 11.6164 3.63208 11.7776 3.55211C11.9176 3.48263 12.082 3.48263 12.222 3.55211C12.3832 3.63208 12.499 3.89177 12.7305 4.41115L14.5745 8.54808C14.643 8.70162 14.6772 8.77839 14.7302 8.83718C14.777 8.8892 14.8343 8.93081 14.8982 8.95929C14.9705 8.99149 15.0541 9.00031 15.2213 9.01795L19.7256 9.49336C20.2911 9.55304 20.5738 9.58288 20.6997 9.71147C20.809 9.82316 20.8598 9.97956 20.837 10.1342C20.8108 10.3122 20.5996 10.5025 20.1772 10.8832L16.8125 13.9154C16.6877 14.0279 16.6252 14.0842 16.5857 14.1527C16.5507 14.2134 16.5288 14.2807 16.5215 14.3503C16.5132 14.429 16.5306 14.5112 16.5655 14.6757L17.5053 19.1064C17.6233 19.6627 17.6823 19.9408 17.5989 20.1002C17.5264 20.2388 17.3934 20.3354 17.2393 20.3615C17.0619 20.3915 16.8156 20.2495 16.323 19.9654L12.3995 17.7024C12.2539 17.6184 12.1811 17.5765 12.1037 17.56C12.0352 17.5455 11.9644 17.5455 11.8959 17.56C11.8185 17.5765 11.7457 17.6184 11.6001 17.7024L7.67662 19.9654C7.18404 20.2495 6.93775 20.3915 6.76034 20.3615C6.60623 20.3354 6.47319 20.2388 6.40075 20.1002C6.31736 19.9408 6.37635 19.6627 6.49434 19.1064L7.4341 14.6757C7.46898 14.5112 7.48642 14.429 7.47814 14.3503C7.47081 14.2807 7.44894 14.2134 7.41394 14.1527C7.37439 14.0842 7.31195 14.0279 7.18708 13.9154L3.82246 10.8832C3.40005 10.5025 3.18884 10.3122 3.16258 10.1342C3.13978 9.97956 3.19059 9.82316 3.29993 9.71147C3.42581 9.58288 3.70856 9.55304 4.27406 9.49336L8.77835 9.01795C8.94553 9.00031 9.02911 8.99149 9.10139 8.95929C9.16534 8.93081 9.2226 8.8892 9.26946 8.83718C9.32241 8.77839 9.35663 8.70162 9.42508 8.54808L11.2691 4.41115Z" stroke="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>