config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: "cars#index"

  resources :cars do
    resources :bookings, only: [:new, :create]
  end

  namespace :profile do
    resources :bookings, only: [:index, :show, :update]
    resources :cars
    root to: "cars#index"
  end

end

app/models/car.rb
class Car < ApplicationRecord
  searchkick
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :brand, presence: true
  validates :model, presence: true
  validates :price_per_day, presence: true
  validates :photos, presence: true
  validates :address, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  def index
    @cars = Car.geocoded
    if params[:query].present?
      @results = Car.search(params[:query])
      @cars_ids = @results.pluck(:id)
      @cars = @cars.where(id: @cars_ids)
    end
    @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { car: }),
        marker_html: render_to_string(partial: "marker", locals: { car: })
      }
    end
  end

  # GET /cars/1
  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/profile/cars_controller.rb
module Profile
  class CarsController < ApplicationController
    before_action :set_car, only: %i[show edit update destroy]

    # GET /cars
    def index
      @cars = Car.where(user: current_user)
    end

    # GET /cars/new
    def new
      @car = Car.new
    end

    # GET /cars/1/edit
    def edit
    end

    # POST /cars
    def create
      @car = Car.new(car_params)
      @car.user = current_user
      return unless @car.save

      redirect_to car_path(@car), notice: "The car has been successfully added.", status: :see_other
    end

    # PATCH/PUT /cars/1
    def update
      if @car.update(car_params)
        redirect_to car_path, notice: "The car has been successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /car/1
    def destroy
      @car.destroy
      redirect_to profile_root_path, notice: "The car has been successfully removed.", status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :model, :price_per_day, :user_id, :address, photos: [])
    end
  end
end

app/views/cars/_info_window.html.erb
<div class="text-start">
  <h5>Information de l'emplacement</h5>
  <hr>
  <p class="mb-0"><strong>Entreprise:</strong> <%= car.brand %></p>
  <p class="mb-0"><strong>Description::</strong> <%= car.model %></p>
  <p class="mb-0"><strong>Prix:</strong> <%= number_with_delimiter(car.price_per_day, delimiter: ',', separator: '.') %>€/Jour</p>
  <p class="mb-0"><strong>Localisation:</strong> <%= car.address %></p>
  <%= link_to "Plus d'infos", car_path(car), class: "btn main-btn" %>

</div>

app/views/cars/_marker.html.erb
<div class="badge rounded-4 bg-primary fs-6">
  <%= car.brand %>
  <%= image_tag "favicon.png", height: 30, width: 30, alt: "Logo" %>
</div>

app/views/cars/index.html.erb
<h1 class="mt-4">Liste des emplacements disponibles</h1>
<div class="row justify-content-cnter">
  <div class="col-sm-12 my-3">
    <%= form_with url: cars_path, method: :get, class: "d-flex" do %>
      <%#= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Rechercher un emplacement"
        %>
      <%#= submit_tag "Rechercher", name: "", class: "btn main-btn" %>
    <% end %>
  </div>
</div>
<div style="width: 100%; height: 300px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <h2 class="mt-4"><strong>Food Truck</strong></h2>
<%= render "shared/cars_list" %>

app/views/cars/show.html.erb
<h1 class="mt-4">Détail de l'emplacement</h1>

<%= render "shared/show_car" %>